title: Alecharp's blog
author: Adrien Lecharpentier
email: "adrien.lecharpentier@gmail.com"
maxWidth: 960px

permalink: pretty

rss_feed: "/atom.xml"
future: false

markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true

exclude: [README.md, LICENSE, *.scss]
